languageCode: en-us
baseURL: "daclaudiu.github.io"
title: "Greetings! 👋 Welcome to My Personal Site"
theme: "PaperMod"
enableEmoji: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
paginate: 15
#googleAnalytics : 

minify:
    disableXML: true
    # minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Claudiu Dumitrescu
    description: Welcome to my personal website! Here you can find information about me, my interests, and my accomplishments. This site may include a portfolio, blog, and contact information to help you get to know me better.
    keywords: [Blog, Personal website, tech, finance]
    author: Claudiu
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: dark # dark, light
    disableThemeToggle: false

    ShowReadingTime: false
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false

    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    assets:
        disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    label:
        text: "Home"
        icon: /apple-touch-icon.png
        iconHeight: 35
    profileMode:
        enabled: true # needs to be explicitly set
        title:  
        subtitle: |
            Hello, I am Claudiu. If you'd like to know more about me, feel free to check out the links provided below. 
        buttons:
            - name: blog 
              url: post
            - name: about me
              url: about

    #homeInfoParams: DONT DELETE ELSE SITE BREAKS 
        Title: 
        Content: |

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/dumitrescuclaudiu"
        - name: github
          url: "https://github.com/daclaudiu"
        - name: medium
          url: "https://medium.com/@claudiu.dumitrescu1"
        - name: twitter
          url: "https://twitter.com/da1claudiu"

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"
    #     bing:
    #         SiteVerificationTag: "XYZabc"
    #     yandex:
    #         SiteVerificationTag: "XYZabc"


cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # editPost:
    #     URL: "https://github.com/adclaudiu/hugo-blog/content"
    #     # Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 1000
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: blog
          name: blog
          url: post
          weight: 20
        - identifier: about me
          name: about me
          url: about
          weight: 20
        - identifier: archive
          name: search
          url: archive
          weight: 40
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai
privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
